export const FORM_FIELDS = {
  FIRST_NAME: 'firstName',
  LAST_NAME: 'lastName',
  EMAIL_ADDRESS: 'emailAddress',
  PASSWORD: 'password',
  PHONE_NUMBER: 'phoneNumber',
  ADDRESS: 'address',
  ADDITIONAL_ADDRESS: 'additionalAddress',
  CITY: 'city',
  STATE: 'state',
  ZIP_CODE: 'zipCode',
  SOCIAL_SECURITY_NUMBER: 'socialSecurityNumber',
  DATE_OF_BIRTH: 'dateOfBirth',
  CITIZENSHIP: 'citizenship',
  INVESTING_EXPERIENCE: 'investingExperience',
  OPTIONS_TRADING_PREFERENCE: 'optionsTradingPreference',
  EMPLOYMENT_STATUS: 'employmentStatus',
  SALARY_RANGE: 'salaryRange',
  EMPLOYER_NAME: 'employerName',
  JOB_DESCRIPTION: 'jobDescription',
  JOB_INDUSTRY: 'jobIndustry',
  JOB_ADDRESS: 'jobAddress',
  JOB_ADDITIONAL_ADDRESS: 'jobAdditionalAddress',
  JOB_CITY: 'jobCity',
  JOB_STATE: 'jobState',
  JOB_ZIP_CODE: 'jobZipCode',
  FAMILY_STATUS: 'familyStatus',
  FAMIlY_EMPLOYMENT: 'familyEmployment',
  EMPLOYMENT_CONFLICT: 'employmentConflict',
  CONFLICT_FIRM_NAME: 'conflictFirmName',
  CONFLICT_EMPLOYEE_NAME: 'conflictEmployeeName',
  CONFLICT_RELATIONSHIP: 'conflictRelationship',
  REPORTED_ALL_INCOME: 'reportedAllIncome',
  MARGIN_ACCOUNT: 'marginAccount',
  DATA_SHARING: 'dataSharing',
  ACCOUNT_FUNDS: 'accountFunds',
};

export const formFieldsInitialState = {
  [FORM_FIELDS.FIRST_NAME]: '',
  [FORM_FIELDS.LAST_NAME]: '',
  [FORM_FIELDS.EMAIL_ADDRESS]: '',
  [FORM_FIELDS.PASSWORD]: '',
  [FORM_FIELDS.PHONE_NUMBER]: '',
  [FORM_FIELDS.ADDRESS]: '',
  [FORM_FIELDS.ADDITIONAL_ADDRESS]: '',
  [FORM_FIELDS.CITY]: '',
  [FORM_FIELDS.STATE]: '',
  [FORM_FIELDS.ZIP_CODE]: '',
  [FORM_FIELDS.SOCIAL_SECURITY_NUMBER]: '',
  [FORM_FIELDS.DATE_OF_BIRTH]: '',
  [FORM_FIELDS.CITIZENSHIP]: '',
  [FORM_FIELDS.INVESTING_EXPERIENCE]: '',
  [FORM_FIELDS.OPTIONS_TRADING_PREFERENCE]: '',
  [FORM_FIELDS.EMPLOYMENT_STATUS]: '',
  [FORM_FIELDS.SALARY_RANGE]: '',
  [FORM_FIELDS.JOB_ADDRESS]: '',
  [FORM_FIELDS.JOB_ADDITIONAL_ADDRESS]: '',
  [FORM_FIELDS.JOB_CITY]: '',
  [FORM_FIELDS.JOB_STATE]: '',
  [FORM_FIELDS.JOB_ZIP_CODE]: '',
  [FORM_FIELDS.EMPLOYER_NAME]: '',
  [FORM_FIELDS.EMPLOYMENT_CONFLICT]: '',
  [FORM_FIELDS.JOB_DESCRIPTION]: '',
  [FORM_FIELDS.JOB_INDUSTRY]: '',
  [FORM_FIELDS.FAMILY_STATUS]: '',
  [FORM_FIELDS.FAMIlY_EMPLOYMENT]: '',
  [FORM_FIELDS.CONFLICT_FIRM_NAME]: '',
  [FORM_FIELDS.CONFLICT_EMPLOYEE_NAME]: '',
  [FORM_FIELDS.CONFLICT_RELATIONSHIP]: '',
  [FORM_FIELDS.REPORTED_ALL_INCOME]: true,
  [FORM_FIELDS.MARGIN_ACCOUNT]: true,
  [FORM_FIELDS.DATA_SHARING]: true,
  [FORM_FIELDS.ACCOUNT_FUNDS]: null,
};

export const formFieldsErrorInitialState = {
  [FORM_FIELDS.FIRST_NAME]: '',
  [FORM_FIELDS.LAST_NAME]: '',
  [FORM_FIELDS.EMAIL_ADDRESS]: '',
  [FORM_FIELDS.PASSWORD]: '',
  [FORM_FIELDS.PHONE_NUMBER]: '',
  [FORM_FIELDS.ADDRESS]: '',
  [FORM_FIELDS.ADDITIONAL_ADDRESS]: '',
  [FORM_FIELDS.CITY]: '',
  [FORM_FIELDS.STATE]: '',
  [FORM_FIELDS.ZIP_CODE]: '',
  [FORM_FIELDS.SOCIAL_SECURITY_NUMBER]: '',
  [FORM_FIELDS.DATE_OF_BIRTH]: '',
  [FORM_FIELDS.CITIZENSHIP]: '',
  [FORM_FIELDS.INVESTING_EXPERIENCE]: '',
  [FORM_FIELDS.OPTIONS_TRADING_PREFERENCE]: '',
  [FORM_FIELDS.EMPLOYMENT_STATUS]: '',
  [FORM_FIELDS.SALARY_RANGE]: '',
  [FORM_FIELDS.JOB_ADDRESS]: '',
  [FORM_FIELDS.JOB_ADDITIONAL_ADDRESS]: '',
  [FORM_FIELDS.JOB_CITY]: '',
  [FORM_FIELDS.JOB_STATE]: '',
  [FORM_FIELDS.JOB_ZIP_CODE]: '',
  [FORM_FIELDS.EMPLOYER_NAME]: '',
  [FORM_FIELDS.EMPLOYMENT_CONFLICT]: '',
  [FORM_FIELDS.JOB_DESCRIPTION]: '',
  [FORM_FIELDS.JOB_INDUSTRY]: '',
  [FORM_FIELDS.FAMILY_STATUS]: '',
  [FORM_FIELDS.FAMIlY_EMPLOYMENT]: '',
  [FORM_FIELDS.CONFLICT_FIRM_NAME]: '',
  [FORM_FIELDS.CONFLICT_EMPLOYEE_NAME]: '',
  [FORM_FIELDS.CONFLICT_RELATIONSHIP]: '',
  [FORM_FIELDS.ACCOUNT_FUNDS]: '',
};

const NONE = 'NONE';
const BEGINNER = 'BEGINNER';
const INTERMEDIATE = 'INTERMEDIATE';
const EXPERT = 'EXPERT';
const YES = 'YES';
const NO = 'NO';
const EMPLOYED = 'EMPLOYED';
const UNEMPLOYED = 'UNEMPLOYED';
const RETIRED = 'RETIRED';
const STUDENT = 'STUDENT';
const VERY_LOW_INCOME = 'VERY_LOW_INCOME';
const LOW_INCOME = 'LOW_INCOME';
const MODERTATE_INCOME = 'MODERTATE_INCOME';
const MID_INCOME = 'MID_INCOME';
const HIGH_INCOME = 'HIGH_INCOME';
const VERY_HIGH_INCOME = 'VERY_HIGH_INCOME';

export const EXPERIENCE_OPTIONS = {
  [NONE]: 'None',
  [BEGINNER]: 'Not Much',
  [INTERMEDIATE]: 'I know what I\'m doing',
  [EXPERT]: 'I\'m an expert',
};

export const OPTIONS_TRADING_AVAILABLE = [
  INTERMEDIATE,
  EXPERT
];

export const OPTIONS_TRADING_PREFERENCES = {
  [YES]: 'Yes',
  [NO]: 'No',
};

export const EMPLOYMENT_OPTIONS = {
  [EMPLOYED]: 'Employed',
  [UNEMPLOYED]: 'Unemployed',
  [RETIRED]: 'Retired',
  [STUDENT]: 'Student',
};

export const INCOME_RANGE_OPTIONS = {
  [VERY_LOW_INCOME]: '$24,999 or less',
  [LOW_INCOME]: '$25,000 to $49,999',
  [MODERTATE_INCOME]: '$50,0000 to $99,999',
  [MID_INCOME]: '$100,000 to $199,999',
  [HIGH_INCOME]: '$200,000 to $499,999',
  [VERY_HIGH_INCOME]: '$500,000 or more',
};

export const FAMILY_OPTIONS = {
  [YES]: 'Yes',
  [NO]: 'No',
};

export const EMPLOYMENT_CONFLICT_OPTIONS = {
  [YES]: 'Yes',
  [NO]: 'No',
};

export const OCCUPATION_DESCRIPTION = [
  'Accountant/Auditor/Bookkeeper',
  'Adjuster',
  'Advertiser/Marketer/PR Professional',
  'Air Traffic Controller',
  'Ambassador/Consulate Professional',
  'Analyst',
  'Appraiser',
  'Architect/Designer',
  'Artist/Performer/Actor/Dancer',
  'Assistant/Executive Assistant',
  'Athlete',
  'Attorney/Judge/Legal Professional',
  'Auctioneer',
  'Banker/Lending Professional',
  'Barber/Beautician/Hairstylist',
  'Broker/Registered Rep',
  'Business Executive',
  'Business Owner',
  'Caregiver',
  'Carpenter/Construction Worker/Contractor',
  'Cashier',
  'Chef/Cook',
  'Chiropractor',
  'Civil Servant',
  'Clergy',
  'Clerk',
  'Compliance/Regulatory Professional',
  'Consultant',
  'Counselor/Therapist',
  'Customer Service Representative',
  'Dealer',
  'Dentist',
  'Distributor',
  'Doctor/Surgeon/Physician',
  'Driver',
  'Engineer',
  'Exterminator',
  'Factory/Warehouse Worker',
  'Farmer/Rancher',
  'Financial Planner/Advisor',
  'Flight Attendant',
  'Human Resources Professional',
  'Importer/Exporter',
  'Inspector/Investigator',
  'Investor',
  'IT Professional/IT Associate',
  'Janitor',
  'Jeweler',
  'Laborer',
  'Landscaper',
  'Mechanic',
  'Military, Officer or Associated',
  'Mortician/Funeral Director',
  'Nurse',
  'Office Associate',
  'Pharmacist',
  'Physical Therapist',
  'Pilot',
  'Police Officer/Firefighter/Law Enforcement Professional',
  'Politician',
  'Project Manager',
  'Real Estate Professional',
  'Researcher',
  'Salesperson',
  'Scientist',
  'Seamstress/Tailor',
  'Security Guard',
  'Social Worker',
  'Teacher/Professor',
  'Technician',
  'Teller',
  'Tradesperson/Craftsperson',
  'Trainer/Instructor',
  'Underwriter',
  'Veterinarian',
  'Writer/Journalist/Editor',
  'Other',
];

export const OCCUPATION_INDUSTRY = [
  'Accounting',
  'Advertising/Marketing',
  'Aerospace/Defense',
  'Agriculture/Forestry',
  'Amusement and Recreation',
  'Animal Services and Veterinary',
  'Architecture/Design',
  'Arts/Antiques',
  'Athletics/Fitness',
  'Automotive',
  'Aviation',
  'Bar/Nightclub/Adult Entertainment Club',
  'Childcare',
  'Cleaning/Janitorial/Housekeeping',
  'Communications/Telecommunications',
  'Construction/Carpentry/Landscaping',
  'Convenience Store/Liquor Store/Gas Station',
  'Customer Service and Support',
  'Education',
  'Embassy/Consulate',
  'Energy',
  'Engineering',
  'Fashion/Clothing',
  'Financial Services',
  'Firearms and Explosives',
  'Gaming/Casino/Card Club',
  'Government/Public Administration',
  'Grocery/Supermarket',
  'Healthcare/Medical Services',
  'Hotel/Hospitality',
  'Import/Export',
  'Information Technology',
  'Insurance',
  'Jewelry, Gems, and Precious Metals',
  'Legal Services/Public Safety',
  'Logistics/Supply Chain',
  'Manufacturing',
  'Maritime',
  'Media/Entertainment',
  'Mining, Oil, and Gas',
  'Money Services Businesses',
  'Non-Profit/NGO/Charity',
  'Parking and Car Washes',
  'Pawn Shops/Brokers',
  'Personal Care/Hygiene',
  'Pharmaceuticals',
  'Printing/Publishing',
  'Professional/Civic Organizations',
  'Real Estate',
  'Religious Organization',
  'Repair Services',
  'Restaurant/Food Service',
  'Retail Sales/Retail Trade',
  'Science and Biotechnology',
  'Security',
  'Transportation',
  'Travel',
  'Utilities',
  'Wholesale Sales/Trade',
  'Other',
]

export const FORM_PAGES = {
  BASIC_INFO: 'basicInfo',
  CONTACT_INFO: 'contactInfo',
  IDENTITY_INFO: 'identityInfo',
  EXPERIENCE_INFO: 'experienceInfo',
  OPTIONS_TRADING_INFO: 'optionsTradingInfo',
  EMPLOYMENT_INFO: 'employmentInfo',
  SALARY_RANGE_INFO: 'salaryRangeInfo',
  EMPLOYMENT_DETAILS: 'employmentDetails',
  EMPLOYMENT_LOCATION_INFO: 'employmentLocationInfo',
  FAMILY_INFO: 'familyInfo',
  FAMILY_EMPLOYMENT_INFO: 'familyEmploymentInfo',
  EMPLOYMENT_CONFLICT_INFO: 'employmentConflictInfo',
  EMPLOYMENT_CONFLICT_DETAILS: 'employmentConlfictDetails',
  TAX_INFO: 'taxInfo',
  APPLICATION_AGREEMENT_INFO: 'applicationAgreementInfo',
  OPTIONAL_FEATURE_AGREEMENTS: 'optionalFeatureAgreements',
  FUND_ACCOUNT_INFO: 'fundAccountInfo',
  FUND_ACCOUNT_DETAILS: 'fundAccountDetails',
};

export const countryPhoneData = {
  AF: { name: "Afghanistan", areaCode: "+93", maxDigitsAllowed: 9 },
  AX: { name: "Åland Islands", areaCode: "+358", maxDigitsAllowed: 9 },
  AL: { name: "Albania", areaCode: "+355", maxDigitsAllowed: 9 },
  DZ: { name: "Algeria", areaCode: "+213", maxDigitsAllowed: 9 },
  AS: { name: "American Samoa", areaCode: "+1-684", maxDigitsAllowed: 7 },
  AD: { name: "Andorra", areaCode: "+376", maxDigitsAllowed: 6 },
  AO: { name: "Angola", areaCode: "+244", maxDigitsAllowed: 9 },
  AI: { name: "Anguilla", areaCode: "+1-264", maxDigitsAllowed: 7 },
  AQ: { name: "Antarctica", areaCode: "", maxDigitsAllowed: 0 },
  AG: { name: "Antigua and Barbuda", areaCode: "+1-268", maxDigitsAllowed: 7 },
  AR: { name: "Argentina", areaCode: "+54", maxDigitsAllowed: 10 },
  AM: { name: "Armenia", areaCode: "+374", maxDigitsAllowed: 8 },
  AW: { name: "Aruba", areaCode: "+297", maxDigitsAllowed: 7 },
  AU: { name: "Australia", areaCode: "+61", maxDigitsAllowed: 9 },
  AT: { name: "Austria", areaCode: "+43", maxDigitsAllowed: 10 },
  AZ: { name: "Azerbaijan", areaCode: "+994", maxDigitsAllowed: 9 },
  BS: { name: "Bahamas", areaCode: "+1-242", maxDigitsAllowed: 7 },
  BH: { name: "Bahrain", areaCode: "+973", maxDigitsAllowed: 8 },
  BD: { name: "Bangladesh", areaCode: "+880", maxDigitsAllowed: 10 },
  BB: { name: "Barbados", areaCode: "+1-246", maxDigitsAllowed: 7 },
  BY: { name: "Belarus", areaCode: "+375", maxDigitsAllowed: 9 },
  BE: { name: "Belgium", areaCode: "+32", maxDigitsAllowed: 9 },
  BZ: { name: "Belize", areaCode: "+501", maxDigitsAllowed: 7 },
  BJ: { name: "Benin", areaCode: "+229", maxDigitsAllowed: 8 },
  BM: { name: "Bermuda", areaCode: "+1-441", maxDigitsAllowed: 7 },
  BT: { name: "Bhutan", areaCode: "+975", maxDigitsAllowed: 7 },
  BO: { name: "Bolivia", areaCode: "+591", maxDigitsAllowed: 8 },
  BA: { name: "Bosnia and Herzegovina", areaCode: "+387", maxDigitsAllowed: 8 },
  BW: { name: "Botswana", areaCode: "+267", maxDigitsAllowed: 8 },
  BR: { name: "Brazil", areaCode: "+55", maxDigitsAllowed: 11 },
  IO: { name: "British Indian Ocean Territory", areaCode: "+246", maxDigitsAllowed: 7 },
  VG: { name: "British Virgin Islands", areaCode: "+1-284", maxDigitsAllowed: 7 },
  BN: { name: "Brunei", areaCode: "+673", maxDigitsAllowed: 7 },
  BG: { name: "Bulgaria", areaCode: "+359", maxDigitsAllowed: 9 },
  BF: { name: "Burkina Faso", areaCode: "+226", maxDigitsAllowed: 8 },
  BI: { name: "Burundi", areaCode: "+257", maxDigitsAllowed: 8 },
  KH: { name: "Cambodia", areaCode: "+855", maxDigitsAllowed: 8 },
  CM: { name: "Cameroon", areaCode: "+237", maxDigitsAllowed: 9 },
  CA: { name: "Canada", areaCode: "+1", maxDigitsAllowed: 10 },
  CV: { name: "Cape Verde", areaCode: "+238", maxDigitsAllowed: 7 },
  KY: { name: "Cayman Islands", areaCode: "+1-345", maxDigitsAllowed: 7 },
  CF: { name: "Central African Republic", areaCode: "+236", maxDigitsAllowed: 8 },
  TD: { name: "Chad", areaCode: "+235", maxDigitsAllowed: 8 },
  CL: { name: "Chile", areaCode: "+56", maxDigitsAllowed: 9 },
  CN: { name: "China", areaCode: "+86", maxDigitsAllowed: 11 },
  CX: { name: "Christmas Island", areaCode: "+61", maxDigitsAllowed: 9 },
  CC: { name: "Cocos (Keeling) Islands", areaCode: "+61", maxDigitsAllowed: 9 },
  CO: { name: "Colombia", areaCode: "+57", maxDigitsAllowed: 10 },
  KM: { name: "Comoros", areaCode: "+269", maxDigitsAllowed: 7 },
  CG: { name: "Congo (Brazzaville)", areaCode: "+242", maxDigitsAllowed: 9 },
  CD: { name: "Congo (Kinshasa)", areaCode: "+243", maxDigitsAllowed: 9 },
  CK: { name: "Cook Islands", areaCode: "+682", maxDigitsAllowed: 7 },
  CR: { name: "Costa Rica", areaCode: "+506", maxDigitsAllowed: 8 },
  HR: { name: "Croatia", areaCode: "+385", maxDigitsAllowed: 9 },
  CU: { name: "Cuba", areaCode: "+53", maxDigitsAllowed: 8 },
  CW: { name: "Curaçao", areaCode: "+599", maxDigitsAllowed: 7 },
  CY: { name: "Cyprus", areaCode: "+357", maxDigitsAllowed: 8 },
  CZ: { name: "Czech Republic", areaCode: "+420", maxDigitsAllowed: 9 },
  DK: { name: "Denmark", areaCode: "+45", maxDigitsAllowed: 8 },
  DJ: { name: "Djibouti", areaCode: "+253", maxDigitsAllowed: 8 },
  DM: { name: "Dominica", areaCode: "+1-767", maxDigitsAllowed: 7 },
  DO: { name: "Dominican Republic", areaCode: "+1-809", maxDigitsAllowed: 10 },
  EC: { name: "Ecuador", areaCode: "+593", maxDigitsAllowed: 9 },
  EG: { name: "Egypt", areaCode: "+20", maxDigitsAllowed: 10 },
  SV: { name: "El Salvador", areaCode: "+503", maxDigitsAllowed: 8 },
  GQ: { name: "Equatorial Guinea", areaCode: "+240", maxDigitsAllowed: 8 },
  ER: { name: "Eritrea", areaCode: "+291", maxDigitsAllowed: 7 },
  EE: { name: "Estonia", areaCode: "+372", maxDigitsAllowed: 8 },
  ET: { name: "Ethiopia", areaCode: "+251", maxDigitsAllowed: 9 },
  FK: { name: "Falkland Islands", areaCode: "+500", maxDigitsAllowed: 6 },
  FO: { name: "Faroe Islands", areaCode: "+298", maxDigitsAllowed: 7 },
  FJ: { name: "Fiji", areaCode: "+679", maxDigitsAllowed: 7 },
  FI: { name: "Finland", areaCode: "+358", maxDigitsAllowed: 9 },
  FR: { name: "France", areaCode: "+33", maxDigitsAllowed: 9 },
  GF: { name: "French Guiana", areaCode: "+594", maxDigitsAllowed: 9 },
  PF: { name: "French Polynesia", areaCode: "+689", maxDigitsAllowed: 7 },
  GA: { name: "Gabon", areaCode: "+241", maxDigitsAllowed: 8 },
  GM: { name: "Gambia", areaCode: "+220", maxDigitsAllowed: 7 },
  GE: { name: "Georgia", areaCode: "+995", maxDigitsAllowed: 9 },
  DE: { name: "Germany", areaCode: "+49", maxDigitsAllowed: 11 },
  GH: { name: "Ghana", areaCode: "+233", maxDigitsAllowed: 9 },
  GI: { name: "Gibraltar", areaCode: "+350", maxDigitsAllowed: 8 },
  GR: { name: "Greece", areaCode: "+30", maxDigitsAllowed: 10 },
  GL: { name: "Greenland", areaCode: "+299", maxDigitsAllowed: 7 },
  GD: { name: "Grenada", areaCode: "+1-473", maxDigitsAllowed: 7 },
  GP: { name: "Guadeloupe", areaCode: "+590", maxDigitsAllowed: 9 },
  GU: { name: "Guam", areaCode: "+1-671", maxDigitsAllowed: 7 },
  GT: { name: "Guatemala", areaCode: "+502", maxDigitsAllowed: 8 },
  GG: { name: "Guernsey", areaCode: "+44-1481", maxDigitsAllowed: 10 },
  GN: { name: "Guinea", areaCode: "+224", maxDigitsAllowed: 8 },
  GW: { name: "Guinea-Bissau", areaCode: "+245", maxDigitsAllowed: 8 },
  GY: { name: "Guyana", areaCode: "+592", maxDigitsAllowed: 8 },
  HT: { name: "Haiti", areaCode: "+509", maxDigitsAllowed: 8 },
  HN: { name: "Honduras", areaCode: "+504", maxDigitsAllowed: 8 },
  HK: { name: "Hong Kong", areaCode: "+852", maxDigitsAllowed: 8 },
  HU: { name: "Hungary", areaCode: "+36", maxDigitsAllowed: 9 },
  IS: { name: "Iceland", areaCode: "+354", maxDigitsAllowed: 7 },
  IN: { name: "India", areaCode: "+91", maxDigitsAllowed: 10 },
  ID: { name: "Indonesia", areaCode: "+62", maxDigitsAllowed: 10 },
  IR: { name: "Iran", areaCode: "+98", maxDigitsAllowed: 10 },
  IQ: { name: "Iraq", areaCode: "+964", maxDigitsAllowed: 10 },
  IE: { name: "Ireland", areaCode: "+353", maxDigitsAllowed: 9 },
  IM: { name: "Isle of Man", areaCode: "+44-1624", maxDigitsAllowed: 9 },
  IL: { name: "Israel", areaCode: "+972", maxDigitsAllowed: 9 },
  IT: { name: "Italy", areaCode: "+39", maxDigitsAllowed: 10 },
  JM: { name: "Jamaica", areaCode: "+1-876", maxDigitsAllowed: 7 },
  JP: { name: "Japan", areaCode: "+81", maxDigitsAllowed: 10 },
  JE: { name: "Jersey", areaCode: "+44-1534", maxDigitsAllowed: 10 },
  JO: { name: "Jordan", areaCode: "+962", maxDigitsAllowed: 9 },
  KZ: { name: "Kazakhstan", areaCode: "+7", maxDigitsAllowed: 10 },
  KE: { name: "Kenya", areaCode: "+254", maxDigitsAllowed: 9 },
  KI: { name: "Kiribati", areaCode: "+686", maxDigitsAllowed: 7 },
  KP: { name: "North Korea", areaCode: "+850", maxDigitsAllowed: 10 },
  KR: { name: "South Korea", areaCode: "+82", maxDigitsAllowed: 10 },
  KW: { name: "Kuwait", areaCode: "+965", maxDigitsAllowed: 8 },
  KG: { name: "Kyrgyzstan", areaCode: "+996", maxDigitsAllowed: 9 },
  LA: { name: "Laos", areaCode: "+856", maxDigitsAllowed: 9 },
  LV: { name: "Latvia", areaCode: "+371", maxDigitsAllowed: 8 },
  LB: { name: "Lebanon", areaCode: "+961", maxDigitsAllowed: 8 },
  LS: { name: "Lesotho", areaCode: "+266", maxDigitsAllowed: 8 },
  LR: { name: "Liberia", areaCode: "+231", maxDigitsAllowed: 8 },
  LY: { name: "Libya", areaCode: "+218", maxDigitsAllowed: 8 },
  LI: { name: "Liechtenstein", areaCode: "+423", maxDigitsAllowed: 8 },
  LT: { name: "Lithuania", areaCode: "+370", maxDigitsAllowed: 8 },
  LU: { name: "Luxembourg", areaCode: "+352", maxDigitsAllowed: 8 },
  MO: { name: "Macao", areaCode: "+853", maxDigitsAllowed: 8 },
  MK: { name: "North Macedonia", areaCode: "+389", maxDigitsAllowed: 8 },
  MG: { name: "Madagascar", areaCode: "+261", maxDigitsAllowed: 8 },
  MW: { name: "Malawi", areaCode: "+265", maxDigitsAllowed: 8 },
  MY: { name: "Malaysia", areaCode: "+60", maxDigitsAllowed: 9 },
  MV: { name: "Maldives", areaCode: "+960", maxDigitsAllowed: 7 },
  ML: { name: "Mali", areaCode: "+223", maxDigitsAllowed: 8 },
  MT: { name: "Malta", areaCode: "+356", maxDigitsAllowed: 8 },
  MH: { name: "Marshall Islands", areaCode: "+692", maxDigitsAllowed: 7 },
  MQ: { name: "Martinique", areaCode: "+596", maxDigitsAllowed: 9 },
  MR: { name: "Mauritania", areaCode: "+222", maxDigitsAllowed: 8 },
  MU: { name: "Mauritius", areaCode: "+230", maxDigitsAllowed: 8 },
  YT: { name: "Mayotte", areaCode: "+262", maxDigitsAllowed: 8 },
  MX: { name: "Mexico", areaCode: "+52", maxDigitsAllowed: 10 },
  FM: { name: "Micronesia", areaCode: "+691", maxDigitsAllowed: 7 },
  MD: { name: "Moldova", areaCode: "+373", maxDigitsAllowed: 8 },
  MC: { name: "Monaco", areaCode: "+377", maxDigitsAllowed: 8 },
  MN: { name: "Mongolia", areaCode: "+976", maxDigitsAllowed: 8 },
  ME: { name: "Montenegro", areaCode: "+382", maxDigitsAllowed: 8 },
  MS: { name: "Montserrat", areaCode: "+1-664", maxDigitsAllowed: 7 },
  MA: { name: "Morocco", areaCode: "+212", maxDigitsAllowed: 9 },
  MZ: { name: "Mozambique", areaCode: "+258", maxDigitsAllowed: 9 },
  MM: { name: "Myanmar", areaCode: "+95", maxDigitsAllowed: 9 },
  NA: { name: "Namibia", areaCode: "+264", maxDigitsAllowed: 8 },
  NR: { name: "Nauru", areaCode: "+674", maxDigitsAllowed: 7 },
  NP: { name: "Nepal", areaCode: "+977", maxDigitsAllowed: 10 },
  NL: { name: "Netherlands", areaCode: "+31", maxDigitsAllowed: 9 },
  NC: { name: "New Caledonia", areaCode: "+687", maxDigitsAllowed: 7 },
  NZ: { name: "New Zealand", areaCode: "+64", maxDigitsAllowed: 8 },
  NI: { name: "Nicaragua", areaCode: "+505", maxDigitsAllowed: 8 },
  NE: { name: "Niger", areaCode: "+227", maxDigitsAllowed: 8 },
  NG: { name: "Nigeria", areaCode: "+234", maxDigitsAllowed: 10 },
  NU: { name: "Niue", areaCode: "+683", maxDigitsAllowed: 7 },
  NF: { name: "Norfolk Island", areaCode: "+672", maxDigitsAllowed: 7 },
  MP: { name: "Northern Mariana Islands", areaCode: "+1-670", maxDigitsAllowed: 7 },
  NO: { name: "Norway", areaCode: "+47", maxDigitsAllowed: 8 },
  OM: { name: "Oman", areaCode: "+968", maxDigitsAllowed: 8 },
  PK: { name: "Pakistan", areaCode: "+92", maxDigitsAllowed: 10 },
  PW: { name: "Palau", areaCode: "+680", maxDigitsAllowed: 7 },
  PS: { name: "Palestine", areaCode: "+970", maxDigitsAllowed: 9 },
  PA: { name: "Panama", areaCode: "+507", maxDigitsAllowed: 8 },
  PG: { name: "Papua New Guinea", areaCode: "+675", maxDigitsAllowed: 8 },
  PY: { name: "Paraguay", areaCode: "+595", maxDigitsAllowed: 8 },
  PE: { name: "Peru", areaCode: "+51", maxDigitsAllowed: 9 },
  PH: { name: "Philippines", areaCode: "+63", maxDigitsAllowed: 10 },
  PN: { name: "Pitcairn", areaCode: "+64", maxDigitsAllowed: 7 },
  PL: { name: "Poland", areaCode: "+48", maxDigitsAllowed: 9 },
  PT: { name: "Portugal", areaCode: "+351", maxDigitsAllowed: 9 },
  PR: { name: "Puerto Rico", areaCode: "+1-787", maxDigitsAllowed: 7 },
  QA: { name: "Qatar", areaCode: "+974", maxDigitsAllowed: 8 },
  RE: { name: "Réunion", areaCode: "+262", maxDigitsAllowed: 8 },
  RO: { name: "Romania", areaCode: "+40", maxDigitsAllowed: 9 },
  RU: { name: "Russia", areaCode: "+7", maxDigitsAllowed: 10 },
  RW: { name: "Rwanda", areaCode: "+250", maxDigitsAllowed: 8 },
  BL: { name: "Saint Barthélemy", areaCode: "+590", maxDigitsAllowed: 9 },
  SH: { name: "Saint Helena", areaCode: "+290", maxDigitsAllowed: 7 },
  KN: { name: "Saint Kitts and Nevis", areaCode: "+1-869", maxDigitsAllowed: 7 },
  LC: { name: "Saint Lucia", areaCode: "+1-758", maxDigitsAllowed: 7 },
  MF: { name: "Saint Martin", areaCode: "+590", maxDigitsAllowed: 9 },
  PM: { name: "Saint Pierre and Miquelon", areaCode: "+508", maxDigitsAllowed: 7 },
  VC: { name: "Saint Vincent and the Grenadines", areaCode: "+1-784", maxDigitsAllowed: 7 },
  WS: { name: "Samoa", areaCode: "+685", maxDigitsAllowed: 7 },
  SM: { name: "San Marino", areaCode: "+378", maxDigitsAllowed: 7 },
  ST: { name: "São Tomé and Príncipe", areaCode: "+239", maxDigitsAllowed: 7 },
  SA: { name: "Saudi Arabia", areaCode: "+966", maxDigitsAllowed: 9 },
  SN: { name: "Senegal", areaCode: "+221", maxDigitsAllowed: 8 },
  RS: { name: "Serbia", areaCode: "+381", maxDigitsAllowed: 9 },
  SC: { name: "Seychelles", areaCode: "+248", maxDigitsAllowed: 7 },
  SL: { name: "Sierra Leone", areaCode: "+232", maxDigitsAllowed: 8 },
  SG: { name: "Singapore", areaCode: "+65", maxDigitsAllowed: 8 },
  SX: { name: "Sint Maarten", areaCode: "+1-721", maxDigitsAllowed: 7 },
  SK: { name: "Slovakia", areaCode: "+421", maxDigitsAllowed: 9 },
  SI: { name: "Slovenia", areaCode: "+386", maxDigitsAllowed: 8 },
  SB: { name: "Solomon Islands", areaCode: "+677", maxDigitsAllowed: 7 },
  SO: { name: "Somalia", areaCode: "+252", maxDigitsAllowed: 8 },
  ZA: { name: "South Africa", areaCode: "+27", maxDigitsAllowed: 9 },
  SS: { name: "South Sudan", areaCode: "+211", maxDigitsAllowed: 8 },
  ES: { name: "Spain", areaCode: "+34", maxDigitsAllowed: 9 },
  LK: { name: "Sri Lanka", areaCode: "+94", maxDigitsAllowed: 8 },
  SD: { name: "Sudan", areaCode: "+249", maxDigitsAllowed: 8 },
  SR: { name: "Suriname", areaCode: "+597", maxDigitsAllowed: 8 },
  SJ: { name: "Svalbard and Jan Mayen", areaCode: "+47", maxDigitsAllowed: 8 },
  SZ: { name: "Eswatini", areaCode: "+268", maxDigitsAllowed: 8 },
  SE: { name: "Sweden", areaCode: "+46", maxDigitsAllowed: 9 },
  CH: { name: "Switzerland", areaCode: "+41", maxDigitsAllowed: 9 },
  SY: { name: "Syria", areaCode: "+963", maxDigitsAllowed: 9 },
  TW: { name: "Taiwan", areaCode: "+886", maxDigitsAllowed: 9 },
  TJ: { name: "Tajikistan", areaCode: "+992", maxDigitsAllowed: 9 },
  TZ: { name: "Tanzania", areaCode: "+255", maxDigitsAllowed: 9 },
  TH: { name: "Thailand", areaCode: "+66", maxDigitsAllowed: 9 },
  TG: { name: "Togo", areaCode: "+228", maxDigitsAllowed: 8 },
  TK: { name: "Tokelau", areaCode: "+690", maxDigitsAllowed: 7 },
  TO: { name: "Tonga", areaCode: "+676", maxDigitsAllowed: 7 },
  TT: { name: "Trinidad and Tobago", areaCode: "+1-868", maxDigitsAllowed: 7 },
  TN: { name: "Tunisia", areaCode: "+216", maxDigitsAllowed: 8 },
  TR: { name: "Turkey", areaCode: "+90", maxDigitsAllowed: 10 },
  TM: { name: "Turkmenistan", areaCode: "+993", maxDigitsAllowed: 9 },
  TC: { name: "Turks and Caicos Islands", areaCode: "+1-649", maxDigitsAllowed: 7 },
  TV: { name: "Tuvalu", areaCode: "+688", maxDigitsAllowed: 7 },
  UG: { name: "Uganda", areaCode: "+256", maxDigitsAllowed: 9 },
  UA: { name: "Ukraine", areaCode: "+380", maxDigitsAllowed: 9 },
  AE: { name: "United Arab Emirates", areaCode: "+971", maxDigitsAllowed: 9 },
  GB: { name: "United Kingdom", areaCode: "+44", maxDigitsAllowed: 10 },
  US: { name: "United States", areaCode: "+1", maxDigitsAllowed: 10 },
  UM: { name: "United States Minor Outlying Islands", areaCode: "+1", maxDigitsAllowed: 10 },
  VI: { name: "U.S. Virgin Islands", areaCode: "+1-340", maxDigitsAllowed: 7 },
  UY: { name: "Uruguay", areaCode: "+598", maxDigitsAllowed: 8 },
  UZ: { name: "Uzbekistan", areaCode: "+998", maxDigitsAllowed: 9 },
  VU: { name: "Vanuatu", areaCode: "+678", maxDigitsAllowed: 7 },
  VA: { name: "Vatican City", areaCode: "+379", maxDigitsAllowed: 7 },
  VE: { name: "Venezuela", areaCode: "+58", maxDigitsAllowed: 9 },
  VN: { name: "Vietnam", areaCode: "+84", maxDigitsAllowed: 10 },
  WF: { name: "Wallis and Futuna", areaCode: "+681", maxDigitsAllowed: 7 },
  EH: { name: "Western Sahara", areaCode: "+212", maxDigitsAllowed: 9 },
  YE: { name: "Yemen", areaCode: "+967", maxDigitsAllowed: 9 },
  ZM: { name: "Zambia", areaCode: "+260", maxDigitsAllowed: 9 },
  ZW: { name: "Zimbabwe", areaCode: "+263", maxDigitsAllowed: 9 },
};
